name: Build and Release

on: [push, pull_request]

jobs:
  build:
    # Указываем, на какой системе собирать мод
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем исходный код вашего мода
      - uses: actions/checkout@v4

      # 2. Устанавливаем и настраиваем Geode SDK
      - name: Setup Geode
        uses: geode-sdk/setup-geode@v1
        with:
          # Указываем версию Geode CLI, которую нужно использовать
          cli: 'latest'
          # Указываем версию Geode SDK
          sdk: 'latest'

      # 3. Собираем мод
      - name: Build Mod
        run: geode build -p android

      # 4. Загружаем готовый файл как артефакт
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: on-keybind-trigger-android
          path: |
            *.geode
            build/Release/*.geode
